name: Test Project

on:
  push:

jobs:
 test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        working-directory: "./02 Starting Project"
        run: npm ci

      - name: Run tests
        working-directory: "./02 Starting Project"
        run: npm test